version: '3.9'
services:

  dynamodb:
    image: amazon/dynamodb-local:2.4.0
    command: "-jar DynamoDBLocal.jar -sharedDb"
    healthcheck:
      test: [ "CMD-SHELL", "curl -v http://dynamodb:8000" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - "8000:8000"
    restart: always

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    ports:
      - "8002:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "ru-central1"
      AWS_ACCESS_KEY_ID: ${STATIC_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${STATIC_KEY_SECRET}
    depends_on:
      dynamodb:
        condition: service_healthy
  
  clickhouse-db:
    image: clickhouse/clickhouse-server:22.6.3.35
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 18123:18123
      - 8123:8123